### ISSUE TITLE
Order complete message and page.

### ISSUE THREAD

**Issue by vincentdavis** [Heteroskedastic/internal-ecom#10]
When an order is complete. What message, information, do you want to show the user and what page do you what them to be directed to?
Option.
- (message) You order is complete and an email invoice has been sent.
- Redirect to store home page.

**Comment by chancock27** [comment]
- Message:

 "Thank you for your order. A confirmation email has been sent."

-  Redirect to store home page

**Comment by vincentdavis** [comment]
see message and action above.
