### ISSUE TITLE
Admin View: Student current status.

### ISSUE THREAD

**Issue by cis-yogesh** [Heteroskedastic/internal-ecom#35]
We have multiple ways to handle student price and count status for Admin 
1)Create View for Admin.
2)Create Event as multiple choose option in "UserProfile".
3)condition if all event has reach up to define value that Userprofile count and price limit set as "0" for that user.

**Comment by vincentdavis** [comment]
The attached image is just an idea. Feel free to improve.
<img width="597" alt="screenshot_87" src="https://cloud.githubusercontent.com/assets/232564/13329469/3a13ebfc-dbb1-11e5-8627-eb077203cae7.png">

**Comment by pprolancer** [comment]
@vincentdavis 
I think we can use a "tree grid" widget for this view.
I had a research and I found this libraries:
http://maxazan.github.io/jquery-treegrid/examples/example-bootstrap-3.html
https://www.jqwidgets.com/jquery-widgets-documentation/documentation/jqxtreegrid/jquery-treegrid-getting-started.htm

**Comment by vincentdavis** [comment]
I like this, go with it.
My only question, The top level can be Events/birthday, but the next level, can we switch between Student and parent?
Maybe we just need 2 different views.
