### ISSUE TITLE
Test cases

### ISSUE THREAD

**Issue by cis-yogesh** [Heteroskedastic/internal-ecom#38]
I have write test cases but they are not working on travic. I think due to setting .
Work on tests is in this branch.
https://github.com/Heteroskedastic/internal-ecom/tree/usertestcases

**Comment by vincentdavis** [comment]
@Shi3A Can you take a look at this. Please branck/fork and make a pull request to fix.

**Comment by Shi3A** [comment]
Ok, I will do it

**Comment by vincentdavis** [comment]
@cis-yogesh, @Shi3A fixed the tests. Continue working on test and then make a pull request to merge to master.
