### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by chancock27** [Heteroskedastic/internal-ecom#8]
This is the content for the about page.  To Do

**Comment by vincentdavis** [comment]
@chancock27 Need the content for this.

**Comment by chancock27** [comment]
Welcome to Cinnamon Hills Student Gift Store. This store was set up to help you more conveniently purchase birthday and holiday gifts for your student.  We hope you are able to find a gift that will enhance your student’s treatment experience.  

During your student’s stay at Cinnamon Hills, they are allowed to receive a limited number of gifts for birthday and holiday.  A student will only be able to receive three items per occasion regardless of how many individuals are attempting to purchase gifts for that student. Please coordinate with anyone else involved in your student’s treatment because they may be attempting to purchase gifts for your student as well.  

Student gifts are organized into three categories:  Activities, Books, and Snacks.  You are allowed to purchase one gift from each category; however, you are not required to purchase three gifts.  Three gifts is simply the limit for each student.  If you have any questions about our gift structure, please call 435-674-0984 and ask for Information Management.

**Comment by vincentdavis** [comment]
@pprolancer use text above
